version: "3"
services:
  app:
    env_file:
      - .env
    container_name: scratchpay_test_task
    # command: sh -c yarn console seed
    restart: always
    build: .
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
    networks:
      - backend

  postgres:
    env_file:
      - .env
    image: postgres
    restart: always
    networks:
      - backend
  
networks:
  backend:
    driver: bridge