apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image.name }}:{{ .Values.db.image.tag }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.db.service.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretName }}
