apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: db
  template:
    metadata:
      labels:
        app.kubernetes.io/component: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image.name }}:{{ .Values.db.image.tag }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secretName }}
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secretName }}
                key: POSTGRES_DB
          ports:
            - containerPort: {{ .Values.db.service.port }}
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", $POSTGRES_USER , "-d", $POSTGRES_DB, "-c", "SELECT 1"]
            initialDelaySeconds: 15
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", $POSTGRES_USER , "-d", $POSTGRES_DB, "-c", "SELECT 1"]
            initialDelaySeconds: 45
            timeoutSeconds: 2
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretName }}
