## This is never pushed, Just pushing for reference of test-task as it contains local settings

## postgres.default.svc.cluster.local, assuming running on default namespace only, change it accordingly.

apiVersion: v1
kind: Secret
metadata:
  name: scratchpay-secrets
stringData:
  PORT: "3000"
  TRANSPORT_PORT: "4000"
  JWT_SECRET_KEY: rxPhglGJWPlOW596
  JWT_EXPIRATION_TIME: "3600"
  FALLBACK_LANGUAGE: en
  DB_HOST: postgres.default.svc.cluster.local
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_DATABASE: spay_task
  NATS_HOST: localhost
  NATS_PORT: "4222"

---

apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: spay_task